name: Test
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      local-path: ${{ steps.build.outputs.local }}
      remote-path: ${{ steps.build.outputs.remote }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build
        id: build
        run: |
          OUTPUT=$(./scripts/build.sh)
          echo "$OUTPUT" >> "$GITHUB_OUTPUT"
        
  upload:
    runs-on: ubuntu-latest
    needs: build
    env:
      LOCAL_PATH: ${{ needs.build.outputs.local-path }}
      REMOTE_PATH: ${{ needs.build.outputs.remote-path }}
    steps:
      - run: |
          echo "Local path is $LOCAL_PATH"
          echo "Remote path is $REMOTE_PATH" 
          
    
