name: Test
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      local-path: ${{ steps.build.outputs.local }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build
        id: build
        run: echo "local=path/to/file" >> "$GITHUB_OUTPUT"
        
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Local path is ${{ needs.build.outputs.local-path }}" 
    
