name: Test
on:
  push:

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Create an empty release
        uses: softprops/actions-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          draft: True
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build
        id: build
        run: |
          OUTPUT=$(./scripts/build.sh)
          echo "$OUTPUT" >> "$GITHUB_OUTPUT"
      - name: Test
        run: cat ${{ steps.build.outputs.local }}
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          LOCAL_PATH: ${{ steps.build.outputs.local }}
          REMOTE_PATH: ${{ steps.build.outputs.remote }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.create_release.outputs.tag-name }}
          files: ${{ env.LOCAL_PATH }}
