name: Test
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      local-path: ${{ steps.build.outputs.local }}
      remote-path: ${{ steps.build.outputs.remote }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build
        id: build
        run: |
          OUTPUT=$(./scripts/build.sh)
          echo "$OUTPUT" >> "$GITHUB_OUTPUT"
        
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: |
          echo "Local path is ${{ needs.build.outputs.local-path }}"
          echo "Remote path is ${{ needs.build.outputs.remote-path }}" 
    
